### ISSUE TITLE
Code clarification

### ISSUE THREAD

**Issue by radiorambo** [manhhungpc/ubuntu2204-svelte#6]
I have read you code completely from first commit to latest to learn how to are these OS clones are being built. I learned a lot. 

And i have some doubts, correct me if I am wrong, but

1. You used CSS majorly to style components and declare variables even when you have tailwind installed. Why? Was this intentional?
2. You used dom manipulation sometimes which as it is generally not recommended when using js frameworks as reactivity system cannot keep track of changes done by direct dom manipulations. Was this intentional?

**Comment by manhhungpc** [comment]
Glad that my project could help you learn something! About your question:

1. Yes, this was intentional. Even though I have tailwind, in a file with too many components, it can easily confuse me as to what a block code does. So I named things in an associative way with meaningful names, and separate css make it more readable too. 
- For example, in `src/components/settings-app/Appearance.svelte`, each section in the Appearance settings is `Style`, `Desktop Icons` and `Dock` so I named them like that to clarify which is which. 
- Color variables for consistent theme and customization.
2. Can you clarify what you mean "dom manipulation", by changing data in an array and re-rendering it? Maybe give some example in my code? I can't remember everything in my code so sorry if I'm misunderstanding.

**Comment by radiorambo** [comment]
1. Why didn't you try [tailwind's component layer](https://tailwindcss.com/docs/adding-custom-styles#adding-component-classes)

2. ![image](https://github.com/manhhungpc/ubuntu2204-svelte/assets/64721943/a8950fdc-f18c-47dd-ab47-f792a569c4fe)

In above code, you handled dom manipulation instead of svelte handling it.
[for more detailed explanation, check this](https://www.phind.com/search?cache=fxjvpyfartvvv0hog5vwn149)

To elaborate my doubt, all I wanted to know is even though you had tailwind installed, you used style block sometimes to style and even having svelte, you handled dom manipulation yourself, my question is it because the above tool usage was anyway limiting in your use case or was it to achieve any kind of performance gain or time saving or was this because you didn't give much thought about it then or any other reason.

And **Thanks for the detailed response** and thanks for open sourcing the code as i gained new knowledge reading it.

🤝

**Comment by manhhungpc** [comment]
1. I want to style blocks with `<style>` tag for each svelte file so I can control the styling better (eventhough it can be repetitive sometimes), rather than write a general class style and apply it. Or me being lazy to customize each components from tailwind component class lol 😂.
2. Oh I remember, Calculator and Terminal are some specific cases where I have to handle dom manipulation by hand because of limitations.
- Like when you type in terminal -> it running (append below input) -> it show the input to type in again. How do I know what input to focus and where to show the next terminal text? I have tried many ways without direct manipulation but always failed - sometime it erase everthing or show text included from previous run in next run ...
So I decide to do it manually, even though it not recommended or efficient.

You can always open a PR for this if you have any better ways to improve this, I'd appreciate it. And thanks for giving me the link about why we should avoid direct dom manipulation in Svelte
